import { bigint, jsonb, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const journeyState = pgEnum("journey_state", ["CREATED", "ATTEMPTED", "FAILED_PENDING_VERIFICATION", "RETRY_ELIGIBLE", "AUTHORIZED", "CAPTURED", "HARD_DECLINED", "EXPIRED", "CANCELLED", "MANUAL_REVIEW"]);
export const paymentJourneys = pgTable("payment_journeys", { id: uuid("id").defaultRandom().primaryKey(), razorpayOrderId: text("razorpay_order_id").unique(), state: journeyState("state").notNull().default("CREATED"), outstandingAmount: bigint("outstanding_amount", { mode: "number" }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const webhookEvents = pgTable("webhook_events", { id: uuid("id").defaultRandom().primaryKey(), razorpayEventId: text("razorpay_event_id").notNull().unique(), eventType: text("event_type").notNull(), payload: jsonb("payload").notNull(), receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow() });
export const recoveryTokens = pgTable("recovery_tokens", { id: uuid("id").defaultRandom().primaryKey(), token: text("token").notNull().unique(), paymentLinkUrl: text("payment_link_url").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true },), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const recoveryDecisions = pgTable("recovery_decisions", { id: uuid("id").defaultRandom().primaryKey(), journeyId: uuid("journey_id").notNull(), action: text("action").notNull(), policy: text("policy").notNull(), predictedSuccess: text("predicted_success"), expectedRecoveryAmount: bigint("expected_recovery_amount", { mode: "number" }).notNull(), safety: jsonb("safety").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const banditStates = pgTable("bandit_states", { id: uuid("id").defaultRandom().primaryKey(), version: text("version").notNull().unique(), featureCount: bigint("feature_count", { mode: "number" }).notNull(), state: jsonb("state").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const auditEntries = pgTable("audit_entries", { id: uuid("id").defaultRandom().primaryKey(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(), eventType: text("event_type").notNull(), evidence: jsonb("evidence").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const banditTrainingInteractions = pgTable("bandit_training_interactions", { id: uuid("id").defaultRandom().primaryKey(), policyVersion: text("policy_version").notNull(), seed: bigint("seed", { mode: "number" }).notNull(), context: jsonb("context").notNull(), action: text("action").notNull(), directRecovery: text("direct_recovery").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
