"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { EmptyState, Icon, SourceBadge, StatusBadge } from "./ui-primitives";
import { LoadingState } from "./loading-state";

type Entry = { id: string; journeyId: string | null; eventType: string; actor: string; entityType: string; entityId: string; action: string | null; reason: string | null; evidence: Record<string, unknown>; previousState: string | null; nextState: string | null; createdAt: string };
const label = (value: string | null | undefined) => (value ?? "Not recorded").replaceAll("_", " ");
function category(entry: Entry) { if (entry.eventType.includes("PAYMENT") || entry.eventType.includes("WEBHOOK") || entry.eventType.includes("CAPTURE")) return "Source event"; if (entry.previousState || entry.nextState) return "State transition"; if (entry.eventType.includes("SAFETY") || entry.eventType.includes("DUPLICATE")) return "Safety evaluation"; if (entry.entityType === "DECISION" || entry.eventType.includes("DECISION")) return "Decision"; if (entry.eventType.includes("WORKFLOW") || entry.eventType.includes("VERIFICATION") || entry.eventType.includes("RECOVERY_LINK")) return "Workflow"; if (entry.eventType.includes("OUTCOME") || entry.eventType.includes("ATTRIBUTE")) return "Outcome"; return "Audit evidence"; }

export function EvidenceLedger() {
  const [entries, setEntries] = useState<Entry[]>(); const [error, setError] = useState(""); const [selected, setSelected] = useState<Entry>(); const [copied, setCopied] = useState("");
  useEffect(() => { const controller = new AbortController(); fetch("/api/audit?page=1&pageSize=50", { signal: controller.signal }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Evidence is unavailable."); setEntries(body.entries); }).catch(cause => { if (!(cause instanceof DOMException && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : "Evidence is unavailable."); }); return () => controller.abort(); }, []);
  useEffect(() => { if (!copied) return; const timer = window.setTimeout(() => setCopied(""), 2200); return () => window.clearTimeout(timer); }, [copied]);
  useEffect(() => { if (!selected) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(undefined); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [selected]);
  const groups = useMemo(() => { const values = new Map<string, Entry[]>(); for (const entry of entries ?? []) { const key = entry.journeyId ?? "unlinked"; values.set(key, [...(values.get(key) ?? []), entry]); } return [...values.entries()]; }, [entries]);
  const copy = async () => { if (!selected) return; try { await navigator.clipboard.writeText(JSON.stringify({ previousState: selected.previousState, nextState: selected.nextState, evidence: selected.evidence, entityId: selected.entityId }, null, 2)); setCopied("Raw evidence copied"); } catch { setCopied("Copy unavailable in this browser"); } };
  if (!entries && !error) return <LoadingState label="Reconciling append-only evidence…" />;
  return <>
    <section className="evidence-ledger"><div className="evidence-ledger-heading"><div><p className="card-label">Append-only financial ledger</p><h2>Trace value through the recovery network</h2><p>Source event → transition → decision → workflow → verified outcome.</p></div><SourceBadge>Evidence-backed</SourceBadge></div>{error ? <p className="state error-state">{error}</p> : groups.length ? <div className="evidence-groups">{groups.map(([journeyId, records]) => <details className="evidence-group" key={journeyId} open><summary><span><strong>{journeyId ?? "System evidence"}</strong><small>{records.length} immutable events</small></span><time>{new Date(records[0].createdAt).toLocaleString()}</time></summary><div className="evidence-chain">{records.map((entry, index) => <article className="evidence-chain-item" key={entry.id}><span className="evidence-step" aria-hidden="true">{index + 1}</span><div><span className="evidence-event"><StatusBadge>{category(entry)}</StatusBadge><strong>{label(entry.eventType)}</strong></span><p>{entry.reason ?? `${entry.actor} recorded ${label(entry.action)}.`}</p><small>{entry.actor} · {entry.entityType} · {new Date(entry.createdAt).toLocaleString()}</small></div><div className="evidence-actions"><button type="button" className="text-button" onClick={() => setSelected(entry)}>Raw JSON</button>{entry.journeyId && <Link href={`/journeys/${entry.journeyId}`}>Journey <Icon name="arrow" /></Link>}</div></article>)}</div></details>)}</div> : <EmptyState title="No audit entries" text="Accepted, ignored, conflicting, and execution events will appear here." />}</section>
    {selected && <div className="evidence-modal"><button className="evidence-backdrop" type="button" onClick={() => setSelected(undefined)} aria-label="Close raw evidence" /><aside className="evidence-drawer" role="dialog" aria-modal="true" aria-labelledby="evidence-drawer-title"><div className="drawer-heading"><div><p className="card-label">Immutable record</p><h2 id="evidence-drawer-title">{label(selected.eventType)}</h2></div><button className="icon-button" type="button" onClick={() => setSelected(undefined)} aria-label="Close raw evidence"><Icon name="close" /></button></div><p className="panel-footnote">{selected.actor} · {new Date(selected.createdAt).toLocaleString()}</p><pre tabIndex={0}>{JSON.stringify({ previousState: selected.previousState, nextState: selected.nextState, evidence: selected.evidence, entityId: selected.entityId }, null, 2)}</pre><button type="button" className="secondary-button" onClick={() => void copy()}><Icon name="evidence" /> Copy raw evidence</button></aside></div>}
    {copied && <div className="toast" role="status">{copied}</div>}
  </>;
}
