"use client";
import { useEffect, useState } from "react";
type Journey = { id: string; orderId: string | null; state: string; outstandingAmount: number; updatedAt: string };
type Detail = { events: Array<{ id: string; type: string; receivedAt: string; amount: number | null }>; workflows: Array<{ action: string; status: string }>; decisions: Array<{ action: string; expectedRecoveryAmount: number; safety: { ruleId?: string } }>; outcome: { category: string; capturedAmount: number } | null };
const rupees = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);
const label = (value: string) => value.replaceAll("_", " ");

export function LiveJourneys() {
  const [journeys, setJourneys] = useState<Journey[]>([]);
  const [selected, setSelected] = useState<string>();
  const [detail, setDetail] = useState<Detail>();
  const [status, setStatus] = useState("");
  useEffect(() => { fetch("/api/journeys", { cache: "no-store" }).then((response) => response.json()).then((data) => setJourneys(data.journeys ?? [])).catch(() => undefined); }, []);
  async function openJourney(id: string) { setSelected(id); setStatus("Loading verified journey evidence…"); setDetail(undefined); const response = await fetch(`/api/journeys/${id}`); const data = await response.json(); if (!response.ok) { setStatus(data.error ?? "Unable to load journey detail."); return; } setDetail(data); setStatus(""); }
  return <section className="panel live-panel"><div className="panel-heading"><div><p className="card-label">Live Test Mode</p><h2>Verified payment journeys</h2></div><span className="safe-pill">Neon-backed</span></div>{journeys.length === 0 ? <p className="panel-footnote">No persisted live journeys yet. Signed Razorpay events will appear here.</p> : <div className="journey-list">{journeys.map((journey) => <button className="journey-row" key={journey.id} onClick={() => openJourney(journey.id)} aria-pressed={selected === journey.id}><span>{journey.orderId ?? "Pending order"}</span><strong>{label(journey.state)}</strong></button>)}</div>}{status && <p className="panel-footnote">{status}</p>}{detail && <div className="journey-detail"><p className="card-label">Journey evidence</p><div className="journey-list"><div className="journey-row"><span>Provider events</span><strong>{detail.events.length}</strong></div>{detail.events.map(event => <div className="journey-row" key={event.id}><span>{label(event.type)} · {new Date(event.receivedAt).toLocaleTimeString()}</span><strong>{event.amount ? rupees(event.amount) : "Verified"}</strong></div>)}{detail.workflows.map((workflow, index) => <div className="journey-row" key={`${workflow.action}-${index}`}><span>Workflow · {label(workflow.action)}</span><strong>{label(workflow.status)}</strong></div>)}{detail.decisions.map((decision, index) => <div className="journey-row" key={`${decision.action}-${index}`}><span>Decision · {label(decision.action)} · {decision.safety.ruleId ?? "RULES"}</span><strong>{rupees(decision.expectedRecoveryAmount)}</strong></div>)}{detail.outcome && <div className="journey-row"><span>Verified outcome · {label(detail.outcome.category)}</span><strong>{rupees(detail.outcome.capturedAmount)}</strong></div>}</div></div>}</section>;
}
