"use client";
import Link from "next/link";
import { useDeferredValue, useEffect, useMemo, useState, type ChangeEvent } from "react";
import { LoadingState } from "./loading-state";
const label=(x:string|undefined|null)=>x?.replaceAll("_"," ")??"—";
const money=(x:number|undefined|null)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format((x??0)/100);
function useData<T>(url:string){const[data,setData]=useState<T>();const[error,setError]=useState("");const[loading,setLoading]=useState(true);useEffect(()=>{const controller=new AbortController();setLoading(true);fetch(url,{cache:"no-store",signal:controller.signal}).then(async r=>{const text=await r.text();const body=text?JSON.parse(text):undefined;if(!r.ok)throw new Error(body?.error??"Evidence unavailable.");if(!body)throw new Error("The server returned an empty response.");setData(body);}).catch(e=>{if(e instanceof DOMException&&e.name==="AbortError")return;setError(e instanceof Error?e.message:"Evidence unavailable.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[url]);return{data,error,loading};}
function Empty({title,text}:{title:string;text:string}){return <div className="empty-state"><strong>{title}</strong><p>{text}</p></div>};function Metric({label,value}:{label:string;value:string}){return <div className="metric-card"><p>{label}</p><strong>{value}</strong></div>}
export function IncidentsScreen(){const{data,error,loading}=useData<any>("/api/incidents");const rows=data?.history??[];return <><p className="source-note">Source: real payment evidence. Simulator incidents remain in Recovery Lab.</p>{error&&<p className="state error-state">{error}</p>}<section className="panel"><div className="panel-heading"><div><p className="card-label">Incident register</p><h2>Open, resolved, and historical incidents</h2></div><span className="status-pill">{loading?"Loading":`${rows.length} records`}</span></div>{loading?<LoadingState label="Loading incident evidence…"/>:rows.length?<div className="table-wrap"><table><thead><tr><th>Status / source</th><th>Cohort</th><th>Baseline → current</th><th>Confidence</th><th>Risk</th><th>Timeline</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td>{label(x.status)}<small>{label(x.source)}</small></td><td>{x.affectedSegment?.label??x.cohortKey}</td><td>{((x.baselineWindow?.successRate??0)*100).toFixed(1)}% → {((x.currentWindow?.successRate??0)*100).toFixed(1)}%</td><td>{x.calibration?.zScore?.toFixed?.(1)??x.confidence}σ</td><td>{x.excessFailureContribution} excess failures<small>{x.downtimeEvidence?.corroborated?"Downtime corroborated":"No downtime corroboration"}</small></td><td>{new Date(x.openedAt).toLocaleString()}<small>{x.closedAt?`Resolved ${new Date(x.closedAt).toLocaleString()}`:"Open"}</small></td></tr>)}</tbody></table></div>:<Empty title="No incidents yet" text="The detector has not persisted an incident meeting its evidence gates."/>}</section></>}
type JourneyFilters = { query:string; state:string; provider:string; method:string; device:string; workflow:string; outcome:string; balance:string; minimum:string; maximum:string; from:string; to:string; sort:string };
type JourneyRow = { id:string; orderId:string|null; state:string; outstandingAmount:number; provider:string|null; method:string|null; device:string|null; workflowStatus:string|null; outcomeCategory:string|null; updatedAt:string };
type JourneyResponse = { journeys:JourneyRow[]; facets:Record<"state"|"provider"|"method"|"device"|"workflow"|"outcome",string[]>; pagination:{page:number; pageSize:number; total:number; totalPages:number} };
type OptionalJourneyFilter = Exclude<keyof JourneyFilters,"query"|"sort">;
const initialJourneyFilters:JourneyFilters={query:"",state:"",provider:"",method:"",device:"",workflow:"",outcome:"",balance:"",minimum:"",maximum:"",from:"",to:"",sort:"recent"};
const journeyFilterLabels:Record<OptionalJourneyFilter,string>={state:"Journey state",provider:"Provider",method:"Payment method",device:"Device",workflow:"Workflow status",outcome:"Outcome",balance:"Outstanding balance",minimum:"Min outstanding",maximum:"Max outstanding",from:"Updated from",to:"Updated to"};

export function JourneysScreen(){
  const[filters,setFilters]=useState<JourneyFilters>(initialJourneyFilters); const[shownFilters,setShownFilters]=useState<OptionalJourneyFilter[]>([]); const[page,setPage]=useState(1); const deferredFilters=useDeferredValue(filters);
  const requestUrl=useMemo(()=>{const params=new URLSearchParams({page:String(page),pageSize:"25"});Object.entries(deferredFilters).forEach(([key,value])=>{if(value)params.set(key,value)});return `/api/journeys?${params}`},[deferredFilters,page]);
  const{data,error,loading}=useData<JourneyResponse>(requestUrl); const rows=data?.journeys??[]; const facets=data?.facets??{state:[],provider:[],method:[],device:[],workflow:[],outcome:[]}; const pagination=data?.pagination;
  const update=(key:keyof JourneyFilters)=>(event:ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>{setPage(1);setFilters(current=>({...current,[key]:event.target.value}));};
  const activeFilters=Object.entries(filters).filter(([key,value])=>key!=="sort"&&value).length;
  const addFilter=(key:OptionalJourneyFilter)=>{if(!shownFilters.includes(key))setShownFilters(current=>[...current,key]);};
  const removeFilter=(key:OptionalJourneyFilter)=>{setPage(1);setShownFilters(current=>current.filter(item=>item!==key));setFilters(current=>({...current,[key]:""}));};
  const select=(key:OptionalJourneyFilter,values:string[]) => <label className="journey-filter"><span>{journeyFilterLabels[key]}</span><select value={filters[key]} onChange={update(key)}><option value="">All</option>{values.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label>;
  return <>
    {error&&<p className="state error-state">{error}</p>}
    <section className="panel journey-filter-panel">
      <div className="panel-heading"><div><p className="card-label">Journey filters</p><h2>Find a payment by any available attribute</h2></div><div className="actions"><span className="status-pill">{pagination?`${pagination.total} matches`:"Loading…"}</span><button type="button" className="text-button" onClick={()=>{setPage(1);setShownFilters([]);setFilters(initialJourneyFilters)}} disabled={!activeFilters&&!shownFilters.length}>Clear filters</button></div></div>
      <div className="journey-filter-toolbar"><label className="journey-filter journey-filter-search"><span>Search</span><input value={filters.query} onChange={update("query")} placeholder="Journey UUID, Razorpay order, state, provider…" aria-label="Search journeys"/></label><label className="journey-filter"><span>Sort</span><select value={filters.sort} onChange={update("sort")}><option value="recent">Most recently updated</option><option value="oldest">Least recently updated</option><option value="outstanding-high">Outstanding: high to low</option><option value="outstanding-low">Outstanding: low to high</option></select></label><label className="journey-filter"><span>Add filter</span><select value="" onChange={event=>addFilter(event.target.value as OptionalJourneyFilter)} aria-label="Add journey filter"><option value="">Choose a filter…</option>{(Object.keys(journeyFilterLabels) as OptionalJourneyFilter[]).filter(key=>!shownFilters.includes(key)).map(key=><option key={key} value={key}>{journeyFilterLabels[key]}</option>)}</select></label></div>
      {shownFilters.length>0&&<div className="journey-filter-grid">
        {shownFilters.includes("state")&&<div className="journey-filter-item">{select("state",facets.state)}<button type="button" aria-label="Remove Journey state filter" onClick={()=>removeFilter("state")}>×</button></div>}{shownFilters.includes("provider")&&<div className="journey-filter-item">{select("provider",facets.provider)}<button type="button" aria-label="Remove Provider filter" onClick={()=>removeFilter("provider")}>×</button></div>}{shownFilters.includes("method")&&<div className="journey-filter-item">{select("method",facets.method)}<button type="button" aria-label="Remove Payment method filter" onClick={()=>removeFilter("method")}>×</button></div>}{shownFilters.includes("device")&&<div className="journey-filter-item">{select("device",facets.device)}<button type="button" aria-label="Remove Device filter" onClick={()=>removeFilter("device")}>×</button></div>}{shownFilters.includes("workflow")&&<div className="journey-filter-item">{select("workflow",facets.workflow)}<button type="button" aria-label="Remove Workflow status filter" onClick={()=>removeFilter("workflow")}>×</button></div>}{shownFilters.includes("outcome")&&<div className="journey-filter-item">{select("outcome",facets.outcome)}<button type="button" aria-label="Remove Outcome filter" onClick={()=>removeFilter("outcome")}>×</button></div>}
        {shownFilters.includes("balance")&&<div className="journey-filter-item"><label className="journey-filter"><span>Outstanding balance</span><select value={filters.balance} onChange={update("balance")}><option value="">Any balance</option><option value="open">Outstanding</option><option value="settled">Settled</option></select></label><button type="button" aria-label="Remove Outstanding balance filter" onClick={()=>removeFilter("balance")}>×</button></div>}{shownFilters.includes("minimum")&&<div className="journey-filter-item"><label className="journey-filter"><span>Min outstanding (paise)</span><input type="number" min="0" value={filters.minimum} onChange={update("minimum")}/></label><button type="button" aria-label="Remove Min outstanding filter" onClick={()=>removeFilter("minimum")}>×</button></div>}{shownFilters.includes("maximum")&&<div className="journey-filter-item"><label className="journey-filter"><span>Max outstanding (paise)</span><input type="number" min="0" value={filters.maximum} onChange={update("maximum")}/></label><button type="button" aria-label="Remove Max outstanding filter" onClick={()=>removeFilter("maximum")}>×</button></div>}{shownFilters.includes("from")&&<div className="journey-filter-item"><label className="journey-filter"><span>Updated from</span><input type="date" value={filters.from} onChange={update("from")}/></label><button type="button" aria-label="Remove Updated from filter" onClick={()=>removeFilter("from")}>×</button></div>}{shownFilters.includes("to")&&<div className="journey-filter-item"><label className="journey-filter"><span>Updated to</span><input type="date" value={filters.to} onChange={update("to")}/></label><button type="button" aria-label="Remove Updated to filter" onClick={()=>removeFilter("to")}>×</button></div>}
      </div>}
    </section>
    <section className="panel"><div className="panel-heading"><div><p className="card-label">Payment journeys</p><h2>Payment lifecycle and recovery status</h2></div><span className="safe-pill">Test Mode / live evidence</span></div>{loading&&!data?<LoadingState label="Loading payment journeys…"/>:rows.length?<><div className="table-wrap"><table><thead><tr><th>Journey / order</th><th>State</th><th>Outstanding</th><th>Provider / method / device</th><th>Workflow</th><th>Outcome</th><th>Updated</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><Link href={`/journeys/${x.id}`}>{x.orderId??x.id}</Link></td><td>{label(x.state)}</td><td>{money(x.outstandingAmount)}</td><td>{[x.provider,x.method,x.device].filter(Boolean).join(" · ")||"Not recorded"}</td><td>{label(x.workflowStatus)}</td><td>{label(x.outcomeCategory)}</td><td>{new Date(x.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></div>{pagination&&<div className="pagination"><span>Page {pagination.page} of {pagination.totalPages} · {pagination.total} journeys</span><div className="actions"><button type="button" disabled={pagination.page===1||loading} onClick={()=>setPage(current=>Math.max(1,current-1))}>Previous</button><button type="button" disabled={pagination.page===pagination.totalPages||loading} onClick={()=>setPage(current=>current+1)}>Next</button></div></div>}</>:<Empty title={pagination?.total?"No journeys match these filters":"No payment journeys"} text={pagination?.total?"Try clearing a filter or widening the amount/date range.":"Signed provider events and simulator runs create journeys here."}/>}</section>
  </>}
export function OperationsScreen(){const{data,error,loading}=useData<any>("/api/operations");return <><p className="source-note">All records below are execution evidence. Amounts are not simulated benchmark results.</p>{error&&<p className="state error-state">{error}</p>}{loading?<section className="panel"><LoadingState label="Loading recovery operations…"/></section>:<><section className="summary-grid compact"><Metric label="Journeys" value={String(data?.journeys??"—")}/><Metric label="Signed events" value={String(data?.signedEvents??"—")}/><Metric label="Captured" value={String(data?.capturedJourneys??"—")}/><Metric label="Pending workflows" value={String(data?.pendingWorkflows??"—")}/></section><section className="panel"><div className="panel-heading"><div><p className="card-label">Recovery workflows</p><h2>Scheduled, executed, stopped, and review work</h2></div></div>{data?.workflows?.length?<div className="table-wrap"><table><thead><tr><th>Journey</th><th>Action / status</th><th>Attempts</th><th>Schedule / execution</th><th>External evidence</th><th>Terminal reason</th></tr></thead><tbody>{data.workflows.map((x:any)=><tr key={x.id}><td><Link href={`/journeys/${x.journeyId}`}>{x.orderId??x.journeyId}</Link></td><td>{label(x.action)}<small>{label(x.status)}</small></td><td>{x.attemptCount}</td><td>{x.scheduledAt?new Date(x.scheduledAt).toLocaleString():"—"}<small>{x.executedAt?`Executed ${new Date(x.executedAt).toLocaleString()}`:"Not executed"}</small></td><td>{x.externalResourceId??x.qstashMessageId??"—"}<small>{x.idempotencyKey??"No idempotency key"}</small></td><td>{x.terminalReason??"—"}</td></tr>)}</tbody></table></div>:<Empty title="No recovery workflows" text="There are no queued, executed, stopped, or review workflows yet."/>}</section></>}</>}
export function AuditScreen(){const{data,error,loading}=useData<any>("/api/audit");return <>{error&&<p className="state error-state">{error}</p>}<section className="panel"><div className="panel-heading"><div><p className="card-label">Immutable audit evidence</p><h2>Trace decisions to payment truth</h2></div><span className="safe-pill">Append-only</span></div>{loading?<LoadingState label="Loading immutable audit evidence…"/>:data?.entries?.length?<div className="audit-list">{data.entries.map((x:any)=><article className="audit-entry" key={x.id}><div><strong>{label(x.eventType)}</strong><p>{x.actor} · {x.entityType} · {x.action??"No action"}</p><p>{x.reason??"No reason recorded."}</p>{x.evidence?.triggerSource&&<p>Recovery trigger: <strong>{label(x.evidence.triggerSource)}</strong></p>}</div><div><time>{new Date(x.createdAt).toLocaleString()}</time>{x.journeyId&&<Link href={`/journeys/${x.journeyId}`}>Open journey →</Link>}</div><details><summary>Evidence and state transition</summary><pre>{JSON.stringify({previousState:x.previousState,nextState:x.nextState,evidence:x.evidence,entityId:x.entityId},null,2)}</pre></details></article>)}</div>:<Empty title="No audit entries" text="Accepted, ignored, conflicting, and execution events will appear here."/>}</section></>}
export function ManualReviewScreen(){const{data,error,loading}=useData<any>("/api/manual-review");const[result,setResult]=useState("");const[acting,setActing]=useState(false);async function act(id:string,action:string){setActing(true);setResult("Applying operator action…");try{const r=await fetch("/api/manual-review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({journeyId:id,action,reason:"Operator action recorded from manual-review queue."})});const b=await r.json();setResult(b.error??b.reason??(b.applied?"Action applied.":"Action was not applied."));}finally{setActing(false)}}return <>{result&&<p className="state">{result}</p>}{error&&<p className="state error-state">{error}</p>}<section className="panel"><div className="panel-heading"><div><p className="card-label">Manual review queue</p><h2>Operator-required payment conflicts</h2></div><span className="status-pill">No auto-approval</span></div>{loading?<LoadingState label="Loading manual-review queue…"/>:data?.queue?.length?<div className="audit-list">{data.queue.map((x:any)=><article className="audit-entry" key={x.id}><div><strong><Link href={`/journeys/${x.id}`}>{x.orderId??x.id}</Link></strong><p>Outstanding: {money(x.outstandingAmount)} · Latest provider state requires a human decision.</p><p>{x.workflows.map((w:any)=>`${label(w.action)} (${label(w.status)})`).join(", ")||"No workflow evidence"}</p></div><div className="actions"><button disabled={acting} onClick={()=>act(x.id,"APPROVE_RECOVERY")}>Approve recovery</button><button disabled={acting} onClick={()=>act(x.id,"STOP_RECOVERY")}>Stop recovery</button></div></article>)}</div>:<Empty title="Queue is clear" text="Hard declines and conflicting financial states are never auto-approved."/>}</section></>}
