"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { LoadingState } from "./loading-state";

type Operations = { journeys: number; signedEvents: number; capturedJourneys: number; pendingWorkflows: number; outcomeTotals: Record<string, number>; recentOutcome: { category: string; createdAt: string } | null; stateTotals: Record<string, number>; recentActivity: Array<{ journeyId: string | null; eventType: string; reason: string | null; createdAt: string }> };
type Incident = { incident: null | { overallBaseline: { successRate: number }; overallCurrent: { successRate: number }; topSegment: { label: string; zScore: number } }; source: string };
const money = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(amount / 100);
const label = (value: string) => value.replaceAll("_", " ");

export function OverviewScreen() {
  const [operations, setOperations] = useState<Operations>();
  const [incident, setIncident] = useState<Incident>();
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([fetch("/api/operations"), fetch("/api/incidents")]).then(async responses => { const bodies = await Promise.all(responses.map(response => response.json())); if (responses.some(response => !response.ok)) throw new Error(bodies.find(body => body.error)?.error ?? "Some command-center evidence is unavailable."); setOperations(bodies[0]); setIncident(bodies[1]); }).catch(cause => setError(cause instanceof Error ? cause.message : "Unable to load command center.")).finally(() => setLoading(false)); }, []);
  if (loading) return <LoadingState label="Loading payment health, active incidents, and recovery activity…" />;
  const totals = operations?.outcomeTotals ?? {}; const states = operations?.stateTotals ?? {};
  return <>
    {error && <p className="state error-state">{error} Some page sections may be unavailable; retry the page when the database connection recovers.</p>}
    <section className="command-intro panel"><div><p className="card-label">Command Center</p><h2>What needs attention now?</h2><p>Find a payment, inspect the current recovery stage, and act only when the state and safety evidence allow it.</p></div><Link className="recovery-button" href="/payments">Find a payment →</Link></section>
    <section className="panel onboarding-guide"><div className="panel-heading"><div><p className="card-label">New operator guide</p><h2>How to work safely in RecoveryOS</h2></div><span className="safe-pill">Evidence first</span></div><ol className="how-it-works"><li>RecoveryOS begins only after a verified provider payment event; a link that was never paid has no failed-payment journey.</li><li>After failure, it waits for late capture or authorization before considering a new recovery path.</li><li>Use Payments to inspect the journey detail, then use a confirmed intervention only when the state machine offers it. Predictions never charge a customer.</li><li>Command Center, Payments, Recovery, and Evidence show persisted operator data. Recovery Lab is synthetic, reproducible, and never combined with operational outcomes.</li></ol></section>
    <section className="summary-grid command-metrics"><Metric label="Current payment success" value={incident?.incident ? `${(incident.incident.overallCurrent.successRate * 100).toFixed(1)}%` : "No active window"} note={incident?.incident ? `Baseline ${(incident.incident.overallBaseline.successRate * 100).toFixed(1)}% · real payment evidence` : "Real/Test Mode evidence"} /><Metric label="Active incident" value={incident?.incident ? incident.incident.topSegment.label : "None detected"} note={incident?.incident ? `${incident.incident.topSegment.zScore.toFixed(1)}σ evidence gate` : "Rolling detector is clear"} /><Metric label="Pending verification" value={String(states.FAILED_PENDING_VERIFICATION ?? 0)} note="RecoveryOS is checking for late capture" /><Metric label="Verified unpaid journeys" value={String(states.RETRY_ELIGIBLE ?? 0)} note="Provider verification found no capture; this is a count, not a revenue estimate" /><Metric label="Autonomous workflows" value={String(operations?.pendingWorkflows ?? "—")} note="Pending controlled work only" /><Metric label="Manual review" value={String(states.MANUAL_REVIEW ?? 0)} note="Operator decision required" /><Metric label="Most recent verified outcome" value={operations?.recentOutcome ? label(operations.recentOutcome.category) : "None yet"} note={operations?.recentOutcome ? `Verified ${new Date(operations.recentOutcome.createdAt).toLocaleString()}` : "Provider evidence only"} /></section>
    <section className="panel"><div className="panel-heading"><div><p className="card-label">Verified outcomes</p><h2>What RecoveryOS recovered, prevented, or could not attribute</h2></div><Link href="/recovery">Open recovery workspace →</Link></div><div className="summary-grid compact"><Metric label="Direct recovery" value={money(totals.DIRECT_RECOVERY ?? 0)} note="Verified direct policy recovery" /><Metric label="Natural late capture" value={money(totals.NATURAL_LATE_CAPTURE ?? 0)} note="Verified capture, not policy recovery" /><Metric label="Unattributed capture" value={money(totals.UNATTRIBUTED_CAPTURE ?? 0)} note="Verified, but not credited to policy" /><Metric label="Not recovered" value={money(totals.NOT_RECOVERED ?? 0)} note="No verified outcome" /><Metric label="Duplicate prevention" value={String(totals.DUPLICATE_PREVENTED ?? 0)} note="Safety guard outcome" /></div><p className="panel-footnote">Amounts are Razorpay Test Mode evidence where a provider capture is recorded. Synthetic Lab data is never included here.</p></section>
    <section className="panel"><div className="panel-heading"><div><p className="card-label">Autonomous Recovery Activity</p><h2>What the system has recently done</h2></div><span className="safe-pill">Real/Test Mode evidence</span></div>{operations?.recentActivity?.length ? <div className="journey-list">{operations.recentActivity.map((activity, index) => <div className="journey-row" key={`${activity.eventType}-${activity.createdAt}-${index}`}><span>{activity.journeyId ? <Link href={`/journeys/${activity.journeyId}`}>{label(activity.eventType)}</Link> : label(activity.eventType)}<small>{activity.reason ?? "Stored system evidence"}</small></span><strong>{new Date(activity.createdAt).toLocaleString()}</strong></div>)}</div> : <div className="empty-state"><strong>Autonomous recovery has not acted yet.</strong><p>Failed payments appear here after a verified payment failure is received.</p></div>}</section>
  </>;
}
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article className="metric-card"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }
