"use client";

import Link from "next/link";
import { ChangeEvent, KeyboardEvent, useEffect, useMemo, useState } from "react";
import { EmptyState, Icon, SourceBadge, StatusBadge } from "./ui-primitives";
import { LoadingState } from "./loading-state";

type Filters = { query: string; state: string; provider: string; method: string; device: string; errorCode: string; workflow: string; outcome: string; balance: string; from: string; to: string; sort: string };
type Row = { id: string; orderId: string | null; providerPaymentId: string | null; state: string; outstandingAmount: number; provider: string | null; method: string | null; device: string | null; workflowStatus: string | null; outcomeCategory: string | null; updatedAt: string };
type Response = { journeys: Row[]; facets: Record<"state" | "provider" | "method" | "device" | "workflow" | "outcome", string[]>; pagination: { page: number; pageSize: number; total: number; totalPages: number } };
const defaults: Filters = { query: "", state: "", provider: "", method: "", device: "", errorCode: "", workflow: "", outcome: "", balance: "", from: "", to: "", sort: "recent" };
const label = (value: string | null | undefined) => (value ?? "Not recorded").replaceAll("_", " ");
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value / 100);

function useLedger(url: string) {
  const [data, setData] = useState<Response>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); fetch(url, { signal: controller.signal }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Payment evidence is unavailable."); setData(body); setError(""); }).catch(cause => { if (!(cause instanceof DOMException && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : "Payment evidence is unavailable."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [url]);
  return { data, error, loading };
}

export function PaymentLedger({ initialQuery = "", initialFilters = {} }: { initialQuery?: string; initialFilters?: Partial<Filters> }) {
  const [filters, setFilters] = useState<Filters>({ ...defaults, ...initialFilters, query: initialQuery || initialFilters.query || "" });
  const [page, setPage] = useState(1); const [advanced, setAdvanced] = useState(false); const [selected, setSelected] = useState<Row>();
  useEffect(() => { const close = (event: KeyboardEvent | globalThis.KeyboardEvent) => { if (event.key === "Escape") setAdvanced(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  const url = useMemo(() => {
    const params = new URLSearchParams({ page: String(page), pageSize: "25" });
    for (const [key, value] of Object.entries(filters)) if (value) params.set(key, value);
    return "/api/journeys?" + params;
  }, [filters, page]);
  const { data, error, loading } = useLedger(url); const rows = data?.journeys ?? []; const facets = data?.facets ?? { state: [], provider: [], method: [], device: [], workflow: [], outcome: [] };
  const change = (key: keyof Filters) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => { setPage(1); setFilters(current => ({ ...current, [key]: event.target.value })); };
  const applied = Object.entries(filters).filter(([key, value]) => value && key !== "query" && key !== "sort");
  const clear = () => { setFilters(defaults); setPage(1); };
  const preset = (state: string) => { setFilters(current => ({ ...defaults, query: current.query, state })); setPage(1); };
  return <>
    <section className="ledger-control" aria-label="Payment search and filters">
      <div className="ledger-title"><div><p className="card-label">Payment ledger</p><h2>Find a payment journey</h2></div><span>{data ? `${data.pagination.total} matches` : "Searching…"}</span></div>
      <div className="ledger-search-row"><label className="ledger-search"><Icon name="search" /><span className="sr-only">Search payments</span><input value={filters.query} onChange={change("query")} placeholder="Search payment ID, order, amount, state…" /></label><button type="button" className="secondary-button" onClick={() => setAdvanced(true)}><Icon name="sidebar" /> Advanced filters</button></div>
      <div className="preset-row" aria-label="Payment views"><button type="button" onClick={() => preset("FAILED_PENDING_VERIFICATION")}>Failed</button><button type="button" onClick={() => preset("RETRY_ELIGIBLE")}>Recovering</button><button type="button" onClick={() => preset("MANUAL_REVIEW")}>Needs review</button><button type="button" onClick={() => preset("CAPTURED")}>Recovered</button>{applied.map(([key, value]) => <button className="filter-chip" type="button" key={key} onClick={() => setFilters(current => ({ ...current, [key]: "" }))}>{label(key)}: {label(value)} <Icon name="close" /></button>)}{(applied.length > 0 || filters.query) && <button className="text-button" type="button" onClick={clear}>Clear all</button>}</div>
    </section>
    {error && <p className="state error-state">{error}</p>}
    <section className="ledger-surface"><div className="ledger-heading"><div><p className="card-label">Payment journeys</p><h2>Lifecycle and recovery state</h2></div><span className="source-legend"><SourceBadge>Test Mode</SourceBadge><SourceBadge synthetic>Synthetic</SourceBadge></span></div>
      {loading && !data ? <LoadingState label="Loading payment ledger…" /> : rows.length ? <div className="table-wrap payment-table"><table><thead><tr><th>Journey / order</th><th>Value path</th><th className="numeric-cell">Outstanding</th><th>Provider</th><th>Workflow</th><th>Outcome</th><th>Updated</th><th><span className="sr-only">Inspect</span></th></tr></thead><tbody>{rows.map(row => { const synthetic = row.orderId?.startsWith("scenario:") ?? false; return <tr key={row.id} className={synthetic ? "synthetic-row" : ""} tabIndex={0} onClick={() => setSelected(row)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(row); } }}><td><strong>{row.orderId ?? row.id}</strong><small>{row.providerPaymentId ?? "Provider payment ID not recorded"}</small><SourceBadge synthetic={synthetic}>{synthetic ? "Synthetic" : "Test Mode"}</SourceBadge></td><td><span className="mini-path" aria-label={`State: ${label(row.state)}`}><i /><i /><i /><strong>{label(row.state)}</strong></span></td><td className="numeric-cell">{money(row.outstandingAmount)}</td><td>{[row.provider, row.method, row.device].filter(Boolean).join(" · ") || "Not recorded"}</td><td><StatusBadge>{label(row.workflowStatus)}</StatusBadge></td><td><StatusBadge>{label(row.outcomeCategory)}</StatusBadge></td><td>{new Date(row.updatedAt).toLocaleString()}</td><td><button type="button" className="row-inspect" onClick={event => { event.stopPropagation(); setSelected(row); }} aria-label={`Inspect ${row.orderId ?? row.id}`}><Icon name="chevron" /></button></td></tr>; })}</tbody></table></div> : <EmptyState title={error ? "Payment evidence unavailable" : "No payment found"} text={error ? "Review the applied filters, then retry. No payment action was taken." : "Try a payment, order, journey, provider, state, or merchant reference."} />}
    </section>
    {advanced && <aside className="filter-drawer" role="dialog" aria-modal="true" aria-labelledby="advanced-filter-title"><div className="drawer-heading"><div><p className="card-label">Ledger controls</p><h2 id="advanced-filter-title">Advanced filters</h2></div><button className="icon-button" type="button" onClick={() => setAdvanced(false)} aria-label="Close advanced filters"><Icon name="close" /></button></div><div className="advanced-filter-grid"><Select title="State" value={filters.state} values={facets.state} onChange={change("state")} /><Select title="Provider" value={filters.provider} values={facets.provider} onChange={change("provider")} /><Select title="Payment method" value={filters.method} values={facets.method} onChange={change("method")} /><Select title="Device" value={filters.device} values={facets.device} onChange={change("device")} /><Input title="Error code" value={filters.errorCode} onChange={change("errorCode")} /><Input title="From" type="date" value={filters.from} onChange={change("from")} /><Input title="To" type="date" value={filters.to} onChange={change("to")} /><Select title="Workflow" value={filters.workflow} values={facets.workflow} onChange={change("workflow")} /><Select title="Outcome" value={filters.outcome} values={facets.outcome} onChange={change("outcome")} /><label><span>Outstanding balance</span><select value={filters.balance} onChange={change("balance")}><option value="">Any balance</option><option value="open">Outstanding</option><option value="settled">Settled</option></select></label><label><span>Sort</span><select value={filters.sort} onChange={change("sort")}><option value="recent">Most recently updated</option><option value="oldest">Least recently updated</option><option value="outstanding-high">Outstanding: high to low</option><option value="outstanding-low">Outstanding: low to high</option></select></label></div><div className="drawer-actions"><button type="button" className="text-button" onClick={clear}>Reset</button><button type="button" className="recovery-button" onClick={() => setAdvanced(false)}>Apply filters</button></div></aside>}
    {selected && <aside className="journey-inspector" role="dialog" aria-modal="true" aria-labelledby="inspector-title"><div className="drawer-heading"><div><p className="card-label">Journey inspector</p><h2 id="inspector-title">{selected.orderId ?? selected.id}</h2></div><button className="icon-button" type="button" onClick={() => setSelected(undefined)} aria-label="Close journey inspector"><Icon name="close" /></button></div><SourceBadge synthetic={selected.orderId?.startsWith("scenario:")}>{selected.orderId?.startsWith("scenario:") ? "Synthetic evidence" : "Razorpay Test Mode evidence"}</SourceBadge><dl className="inspector-list"><div><dt>Outstanding amount</dt><dd>{money(selected.outstandingAmount)}</dd></div><div><dt>Provider</dt><dd>{selected.provider ?? "Not recorded"}</dd></div><div><dt>Current state</dt><dd>{label(selected.state)}</dd></div><div><dt>Most recent transition</dt><dd>{new Date(selected.updatedAt).toLocaleString()}</dd></div><div><dt>What happens next</dt><dd>{selected.workflowStatus === "PENDING" ? "Provider verification remains scheduled." : "Open the full journey for the persisted decision and safety evidence."}</dd></div></dl><Link className="recovery-button" href={`/journeys/${selected.id}`}>Open full journey <Icon name="arrow" /></Link></aside>}
  </>;
}

function Select({ title, value, values, onChange }: { title: string; value: string; values: string[]; onChange: (event: ChangeEvent<HTMLSelectElement>) => void }) { return <label><span>{title}</span><select value={value} onChange={onChange}><option value="">All</option>{values.map(value => <option value={value} key={value}>{label(value)}</option>)}</select></label>; }
function Input({ title, type = "text", value, onChange }: { title: string; type?: string; value: string; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label><span>{title}</span><input type={type} value={value} onChange={onChange} /></label>; }
