import { createHash } from "node:crypto";
import { and, desc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { env } from "@/lib/env";
import { createDatabase } from "@/db/client";
import { auditEntries, banditStates, paymentAttempts, paymentJourneys, paymentStateTransitions, recoveryDecisions, recoveryOutcomes, recoveryTokens, recoveryWorkflows, webhookEvents } from "@/db/schema";
import { mapRazorpayEvent } from "@/lib/razorpay/event-mapping";
import { verifyRazorpayWebhook } from "@/lib/razorpay/webhook";
import { applyPaymentEvent } from "@/lib/recovery/journey-updater";
import { attributeOutcome } from "@/lib/recovery/outcome-attribution";
import { restoreBanditState, serializeBanditState } from "@/lib/recovery/bandit-persistence";
import { updateLinUcb } from "@/lib/recovery/linucb";
import { encodeRecoveryContext, type RecoveryPolicyContext } from "@/lib/recovery/policy-context";
import { recoveryActions, type RecoveryAction } from "@/lib/recovery/safety-policy";
import { cancelVerification, scheduleVerification } from "@/lib/recovery/verification-job";

type PaymentEntity = { id?: string; order_id?: string; amount?: number; currency?: string; payment_link_id?: string; method?: string; bank?: string; status?: string; error_code?: string; error_source?: string; error_step?: string; error_reason?: string; created_at?: number; notes?: Record<string, unknown> };

export async function POST(request: Request) {
  try {
    const rawBody = await request.text();
    const webhook = verifyRazorpayWebhook(rawBody, request.headers.get("x-razorpay-signature"), request.headers.get("x-razorpay-event-id"), env.RAZORPAY_WEBHOOK_SECRET);
    const database = createDatabase();
    const result = await database.transaction(async tx => {
      const [event] = await tx.insert(webhookEvents).values({ razorpayEventId: webhook.eventId, eventType: webhook.eventType, payload: webhook.payload, payloadDigest: digest(rawBody), processingResult: "RECEIVED" }).onConflictDoNothing().returning({ id: webhookEvents.id });
      if (!event) return { duplicate: true as const };
      const entity = paymentEntity(webhook.payload); const paymentEvent = mapRazorpayEvent(webhook.eventType);
      if (!paymentEvent || !entity?.order_id || !entity.amount) {
        await tx.update(webhookEvents).set({ processingResult: "IGNORED_INVALID_PAYLOAD", processingReason: "Unsupported event or missing payment order/amount.", processedAt: new Date() }).where(eq(webhookEvents.id, event.id));
        await tx.insert(auditEntries).values({ webhookEventId: event.id, entityType: "WEBHOOK_EVENT", entityId: event.id, action: "IGNORE", eventType: "PAYMENT_EVENT_IGNORED", reason: "Unsupported event or missing payment order/amount.", evidence: { eventId: webhook.eventId, eventType: webhook.eventType } });
        return { ignored: true as const };
      }
      const [token] = entity.payment_link_id ? await tx.select().from(recoveryTokens).where(eq(recoveryTokens.paymentLinkId, entity.payment_link_id)).limit(1) : [];
      const [existing] = token?.journeyId ? await tx.select().from(paymentJourneys).where(eq(paymentJourneys.id, token.journeyId)).limit(1) : await tx.select().from(paymentJourneys).where(eq(paymentJourneys.razorpayOrderId, entity.order_id)).limit(1);
      const journey = existing ?? (await tx.insert(paymentJourneys).values({ razorpayOrderId: entity.order_id, providerPaymentId: entity.id, originalAmount: entity.amount, outstandingAmount: entity.amount, currency: entity.currency ?? "INR", paymentMethod: entity.method, provider: entity.bank, deviceCategory: device(entity) }).returning())[0]!;
      const occurredAt = providerTime(entity.created_at);
      const [attempt] = await tx.insert(paymentAttempts).values({ journeyId: journey.id, providerPaymentId: entity.id, providerOrderId: entity.order_id, amount: entity.amount, currency: entity.currency ?? "INR", method: entity.method, provider: entity.bank, deviceCategory: device(entity), status: entity.status ?? webhook.eventType, errorCode: entity.error_code, errorSource: entity.error_source, errorStep: entity.error_step, errorReason: entity.error_reason, providerOccurredAt: occurredAt, metadata: { paymentLinkId: entity.payment_link_id ?? null } }).onConflictDoUpdate({ target: paymentAttempts.providerPaymentId, set: { status: entity.status ?? webhook.eventType, errorCode: entity.error_code, errorSource: entity.error_source, errorStep: entity.error_step, errorReason: entity.error_reason, providerOccurredAt: occurredAt } }).returning({ id: paymentAttempts.id });
      await tx.update(webhookEvents).set({ journeyId: journey.id, paymentAttemptId: attempt!.id, providerOccurredAt: occurredAt }).where(eq(webhookEvents.id, event.id));
      const next = applyPaymentEvent({ state: journey.state, outstandingAmount: journey.outstandingAmount }, paymentEvent); const accepted = next.state !== journey.state || next.outstandingAmount !== journey.outstandingAmount;
      await tx.insert(paymentStateTransitions).values({ journeyId: journey.id, webhookEventId: event.id, previousState: journey.state, nextState: next.state, accepted, reason: accepted ? `${webhook.eventType} applied.` : `${webhook.eventType} ignored for ${journey.state}.`, occurredAt });
      await tx.insert(auditEntries).values({ journeyId: journey.id, webhookEventId: event.id, entityType: "JOURNEY", entityId: journey.id, action: accepted ? "TRANSITION" : "IGNORE", eventType: accepted ? "PAYMENT_STATE_UPDATED" : "PAYMENT_STATE_IGNORED", reason: accepted ? "Valid state transition." : "State transition is not valid for the current journey.", previousState: journey.state, nextState: next.state, evidence: { eventId: webhook.eventId, eventType: webhook.eventType, paymentAttemptId: attempt!.id } });
      if (!accepted) { await tx.update(webhookEvents).set({ processingResult: "IGNORED_TRANSITION", processingReason: `${webhook.eventType} is not valid for ${journey.state}.`, processedAt: new Date() }).where(eq(webhookEvents.id, event.id)); return { ignored: true as const }; }
      await tx.update(paymentJourneys).set({ state: next.state, outstandingAmount: next.outstandingAmount, providerPaymentId: entity.id ?? journey.providerPaymentId, paymentMethod: entity.method ?? journey.paymentMethod, provider: entity.bank ?? journey.provider, deviceCategory: device(entity) ?? journey.deviceCategory, terminalOutcome: next.state === "CAPTURED" ? "CAPTURED" : journey.terminalOutcome, updatedAt: new Date() }).where(eq(paymentJourneys.id, journey.id));
      let scheduled: { journeyId: string; workflowId: string; idempotencyKey: string; runAt: Date } | undefined; let cancelMessageIds: string[] = [];
      if (next.state === "CAPTURED") { const pending = await tx.select({ id: recoveryWorkflows.id, qstashMessageId: recoveryWorkflows.qstashMessageId }).from(recoveryWorkflows).where(and(eq(recoveryWorkflows.journeyId, journey.id), eq(recoveryWorkflows.status, "PENDING"))); if (pending.length) { await tx.update(recoveryWorkflows).set({ status: "STOPPED", terminalReason: "CAPTURED", cancelledAt: new Date(), updatedAt: new Date() }).where(and(eq(recoveryWorkflows.journeyId, journey.id), eq(recoveryWorkflows.status, "PENDING"))); cancelMessageIds = pending.flatMap(workflow => workflow.qstashMessageId ? [workflow.qstashMessageId] : []); } if (token || journey.state === "FAILED_PENDING_VERIFICATION" || journey.state === "RETRY_ELIGIBLE") await recordOutcome(tx, { journey, token, entity, eventId: event.id, providerEventId: webhook.eventId }); }
      if (next.state === "FAILED_PENDING_VERIFICATION") { const runAt = new Date(Date.now() + env.RECOVERY_GRACE_PERIOD_SECONDS * 1000); const idempotencyKey = `verify:${journey.id}:${event.id}`; const [workflow] = await tx.insert(recoveryWorkflows).values({ journeyId: journey.id, action: "WAIT_AND_VERIFY", status: "PENDING", idempotencyKey, attemptCount: 0, expiresAt: runAt }).onConflictDoNothing().returning({ id: recoveryWorkflows.id }); if (workflow) { await tx.insert(auditEntries).values({ journeyId: journey.id, webhookEventId: event.id, entityType: "WORKFLOW", entityId: workflow.id, action: "SCHEDULE", eventType: "VERIFICATION_CREATED", reason: "Recoverable failure requires late-authorization verification.", evidence: { journeyId: journey.id, runAt: runAt.toISOString(), gracePeriodSeconds: env.RECOVERY_GRACE_PERIOD_SECONDS } }); scheduled = { journeyId: journey.id, workflowId: workflow.id, idempotencyKey, runAt }; } }
      await tx.update(webhookEvents).set({ processingResult: "APPLIED", processingReason: "Payment event processed transactionally.", processedAt: new Date() }).where(eq(webhookEvents.id, event.id));
      return { scheduled, cancelMessageIds };
    });
    if ("duplicate" in result) return NextResponse.json({ accepted: true, duplicate: true });
    if ("cancelMessageIds" in result) await Promise.all((result.cancelMessageIds ?? []).map(messageId => cancelVerification(messageId).catch(() => false)));
    if ("scheduled" in result && result.scheduled) { const job = result.scheduled; const destination = `${process.env.APP_BASE_URL ?? ""}/api/jobs/verify-payment`; const scheduled = await scheduleVerification({ journeyId: job.journeyId, workflowId: job.workflowId, idempotencyKey: job.idempotencyKey, expectedState: "FAILED_PENDING_VERIFICATION", runAt: job.runAt }, destination).catch((): { scheduled: false; messageId?: string } => ({ scheduled: false })); if (scheduled.scheduled) await database.update(recoveryWorkflows).set({ scheduledAt: new Date(), qstashMessageId: scheduled.messageId, updatedAt: new Date() }).where(eq(recoveryWorkflows.id, job.workflowId)); }
    return NextResponse.json({ accepted: true, event: webhook.eventType, ignored: "ignored" in result && result.ignored });
  } catch (error) { return NextResponse.json({ accepted: false, error: error instanceof Error ? error.message : "Webhook rejected" }, { status: 400 }); }
}

async function recordOutcome(tx: Parameters<ReturnType<typeof createDatabase>["transaction"]>[0] extends (tx: infer T) => unknown ? T : never, input: { journey: typeof paymentJourneys.$inferSelect; token: typeof recoveryTokens.$inferSelect | undefined; entity: PaymentEntity; eventId: string; providerEventId: string }) {
  const [decision] = input.token?.decisionId ? await tx.select().from(recoveryDecisions).where(eq(recoveryDecisions.id, input.token.decisionId)).limit(1) : await tx.select().from(recoveryDecisions).where(eq(recoveryDecisions.journeyId, input.journey.id)).orderBy(desc(recoveryDecisions.createdAt)).limit(1);
  const attributed = attributeOutcome({ action: decision?.action === "CREATE_PAYMENT_LINK" ? "CREATE_PAYMENT_LINK" : "WAIT_AND_VERIFY", predictedSuccess: Number(decision?.predictedSuccess ?? 0), expectedRecoveryAmount: decision?.expectedRecoveryAmount ?? input.journey.outstandingAmount, policyVersion: decision?.policyVersion ?? decision?.policy ?? "RULES" }, { capturedAmount: input.entity.amount!, captureVerified: true, captureFlowToken: input.token?.tokenDigest, recoveryFlowToken: input.token?.tokenDigest, capturedDuringGracePeriod: input.journey.state === "FAILED_PENDING_VERIFICATION" && !input.token });
  const [outcome] = await tx.insert(recoveryOutcomes).values({ journeyId: input.journey.id, decisionId: decision?.id, webhookEventId: input.eventId, outcomeKey: `CAPTURE:${input.providerEventId}`, category: attributed.category, capturedAmount: input.entity.amount!, expectedRecoveryAmount: decision?.expectedRecoveryAmount ?? input.journey.outstandingAmount, policyReward: attributed.policyReward, evidence: { eventId: input.providerEventId, paymentLinkId: input.entity.payment_link_id ?? null, directRecovery: Boolean(input.token), decisionId: decision?.id ?? null } }).onConflictDoNothing().returning({ id: recoveryOutcomes.id });
  if (!outcome) return;
  await tx.insert(auditEntries).values({ journeyId: input.journey.id, webhookEventId: input.eventId, decisionId: decision?.id, outcomeId: outcome.id, entityType: "OUTCOME", entityId: outcome.id, action: "ATTRIBUTE", eventType: "CAPTURE_ATTRIBUTED", reason: "Provider-verified capture.", evidence: { journeyId: input.journey.id, category: attributed.category, capturedAmount: input.entity.amount, webhookEventId: input.eventId } });
  if (attributed.category === "DIRECT_RECOVERY" && decision?.policy === "LINUCB" && decision.policyVersion && isRecoveryAction(decision.action) && isRecoveryPolicyContext(decision.policyContext)) { const [stored] = await tx.select().from(banditStates).where(eq(banditStates.version, decision.policyVersion)).limit(1); if (stored) { const updated = updateLinUcb(restoreBanditState(JSON.stringify(stored.state)), decision.action, encodeRecoveryContext(decision.policyContext), true); await tx.update(banditStates).set({ state: JSON.parse(serializeBanditState(updated)), updatedAt: new Date() }).where(eq(banditStates.version, decision.policyVersion)); await tx.insert(auditEntries).values({ journeyId: input.journey.id, decisionId: decision.id, outcomeId: outcome.id, entityType: "POLICY", entityId: decision.policyVersion, action: "LEARN", eventType: "LINUCB_UPDATED", reason: "Verified direct recovery.", evidence: { decisionId: decision.id, outcomeId: outcome.id, action: decision.action, reward: attributed.policyReward, context: decision.policyContext } }); } }
}

function paymentEntity(payload: unknown): PaymentEntity | null { return payload && typeof payload === "object" ? (payload as { payload?: { payment?: { entity?: PaymentEntity } } }).payload?.payment?.entity ?? null : null; }
function digest(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function providerTime(seconds: number | undefined): Date { return seconds ? new Date(seconds * 1000) : new Date(); }
function device(entity: PaymentEntity): string | undefined { return typeof entity.notes?.device === "string" ? entity.notes.device.toUpperCase() : undefined; }
function isRecoveryAction(value: string): value is RecoveryAction { return recoveryActions.includes(value as RecoveryAction); }
function isRecoveryPolicyContext(value: unknown): value is RecoveryPolicyContext { if (!value || typeof value !== "object") return false; const c = value as Partial<RecoveryPolicyContext>; return typeof c.amount === "number" && typeof c.attemptNumber === "number" && typeof c.minutesSinceFailure === "number" && typeof c.hourOfDay === "number" && typeof c.method === "string" && typeof c.provider === "string" && typeof c.errorCode === "string" && typeof c.device === "string" && typeof c.activeIncident === "boolean" && [0, 1, 2, 3].includes(c.downtimeSeverity ?? -1); }
